apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
data:
  fluentd.conf: |
    <source>
      type tail
      format none
      path /usr/share/log/root.log
      pos_file /usr/share/log/root.log.pos
      tag kayak-app.format1
    </source>


    <match **>
      type google_cloud
    </match>
---
apiVersion: v1  
kind: Service  
metadata:  
  name: kayak-service  
  labels:  
    app: kayak-service  
spec:  
  ports:  
    - name: http  
      port: 8000  
  selector:  
    app: kayak-service  
---  
apiVersion: extensions/v1beta1  
kind: Deployment  
metadata:  
  name: kayak-service  
spec:  
  replicas: 1  
  template:  
    metadata:  
      labels:  
        app: kayak-service  
        version: v1  
    spec:  
      containers:  
        - name: kayak-app  
          image: gcr.io/spring-boot-gke-244822/kayak-app:1.4
          imagePullPolicy: IfNotPresent  
          env:  
            - name: MONGODB_HOST  
              value: mongodb  
          ports:  
            - containerPort: 8000  
          livenessProbe:  
            httpGet:  
              path: /  
              port: 8000  
            initialDelaySeconds: 5  
            periodSeconds: 5
          volumeMounts:
          - name: usrlog
            mountPath: /usr/share/log
          - name: varlog
            mountPath: /var/log
        - name: count-agent-app
          image: busybox
          args: [/bin/sh, -c, 'tail -n+1 -f /usr/share/log/kayak.log']
          volumeMounts:
          - name: usrlog
            mountPath: /usr/share/log
          - name: varlog
            mountPath: /var/log
        - name: count-agent-root
          image: k8s.gcr.io/fluentd-gcp:1.30
          env:
          - name: FLUENTD_ARGS
            value: -c /etc/fluentd-config/fluentd.conf
          volumeMounts:
          - name: usrlog
            mountPath: /usr/share/log
          - name: config-volume
            mountPath: /etc/fluentd-config
          - name: varlog
            mountPath: /var/log
      volumes:
      - name: usrlog
        persistentVolumeClaim:
          claimName: kayak-pv-claim2
      - name: config-volume
        configMap:
          name: fluentd-config
      - name: varlog
        emptyDir: {}
