apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
data:
  fluentd.conf: |
    <source>
      type tail
      format none
      path /var/log/root.log
      pos_file /var/log/root.log.pos
      tag kayak-service.format1
    </source>

    <source>
      type tail
      format none
      path /var/log/kayak.log
      pos_file /var/log/kayak.log.pos
      tag kayak-service.format2
    </source>

    <match **>
      type google_cloud
    </match>
